name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, wolrd!
    - name: Ruan a multi-line script
      run: |
        echo Add other action to build,
        echo test, and deploy your project
    
